<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

define('CLI_SCRIPT', true);

require_once(dirname(__FILE__) . '/../../../config.php');
require_once($CFG->libdir . '/clilib.php');
require_once($CFG->dirroot . '/user/lib.php');

$users = array(
    array('sb453', 'Steve', 'Bailey'),
    array('sb453', 'Steve', 'Bailey'),
    array('sc346', 'Sebastien', 'Cadinot'),
    array('jrn5', 'Ruth', 'Newman'),
    array('ks507', 'Kieran', 'Shand'),
    array('hjw', 'Helen', 'Winder'),
    array('am595', 'Anthony', 'Manning'),
    array('gjm32', 'Georgia', 'Miller'),
    array('jg319', 'Jessica', 'Gilbert'),
    array('kab56', 'Katie', 'Baldock'),
    array('sc5', 'Sandra', 'Shine'),
    array('mcw', 'Mark', 'Wheadon'),
    array('tdb', 'Tim', 'Bishop'),
    array('rjh1', 'Rosemary', 'Higham'),
    array('das', 'Deborah', 'Sillifant'),
    array('sm558', 'Sam', 'McDonagh'),
    array('jgj', 'Janine', 'Jarvis'),
    array('lj212', 'L.T.', 'Jackson'),
    array('la269', 'Lucy', 'Ashbey'),
    array('sv39', 'Sonnary', 'Dearden'),
    array('jt307', 'Julie', 'Teulings'),
    array('tb222', 'Thomas', 'Bore'),
    array('smg', 'Shivaun', 'Gammie'),
    array('rl222', 'Ruey-Leng', 'Loo'),
    array('ssw', 'Scott S.P.', 'Wildman'),
    array('vs59', 'Vadim', 'Sumbayev'),
    array('cd261', 'C.', 'Diaper'),
    array('jm294', 'Joanna', 'Mowbray'),
    array('rh379', 'R.N.', 'Hammersley'),
    array('hs235', 'Hayley', 'Smith'),
    array('ah421', 'Andrew', 'Hall'),
    array('tsg3', 'T.S.', 'Gill'),
    array('mak23', 'Min', 'Keating'),
    array('mnm', 'M.N.', 'Momin'),
    array('es340', 'E.', 'Scahill'),
    array('amb54', 'Alison', 'Bratt'),
    array('jr323', 'Janey', 'Robertson'),
    array('yu', 'Yuri', 'Ushkaryov'),
    array('vg65', 'Vladimir', 'Gubala'),
    array('ib71', 'I.', 'Bailey'),
    array('am582', 'Andrea', 'Manfrin'),
    array('rmw', 'Rob', 'White'),
    array('jhajd', 'Jerome', 'Durodie'),
    array('an76', 'Ali', 'Nokhodchi'),
    array('aam23', 'Alistair', 'Mathie'),
    array('anl', 'Andrew', 'Lea'),
    array('dl311', 'Daniel', 'Lee'),
    array('ew208', 'Elizabeth', 'Worthing'),
    array('jfw4', 'John', 'Whitmore'),
    array('kc329', 'K.', 'Coughlan'),
    array('kic', 'Iain', 'Cumming'),
    array('mac', 'Maxwell', 'Casely-Hayford'),
    array('rmr', 'Ruth', 'Rodgers'),
    array('spk21', 'Stephen', 'Kelley'),
    array('sg260', 'Stuart', 'Gill-Banham'),
    array('nt96', 'Nigel', 'Temperton'),
    array('tg41', 'Taravat', 'Ghafourian'),
    array('sac47', 'Sarah', 'Corlett'),
    array('km439', 'K.M.', 'Patel'),
    array('aae', 'Alison', 'Edwards'),
    array('nl48', 'Nathalie', 'Lavignac'),
    array('ng290', 'Naomi', 'Gordon'),
    array('cb355', 'Cleopatra', 'Branch'),
    array('cd265', 'Catherine', 'Dewsbury'),
    array('gl53', 'Gurprit', 'Lall'),
    array('sds', 'Simon', 'Scott'),
    array('gw244', 'G.', 'Wray-French'),
    array('ba75', 'Bugewa', 'Apampa'),
    array('tt41', 'Trudy', 'Thomas'),
    array('lal22', 'Linda', 'Lucas'),
    array('cmp34', 'Claire', 'Peppiatt'),
    array('cmp36', 'C.M.', 'Peppaitt-Wildman'),
    array('mh527', 'M.', 'Hatherly'),
    array('jrr', 'James', 'Redmond'),
    array('dcs', 'Dean', 'Sayle'),
    array('klh', 'Kim', 'Harty'),
    array('pnc', 'Paul', 'Cornwall'),
    array('db400', 'Derek', 'Baldwin'),
    array('kad5', 'Kim', 'Dawkins'),
    array('mz93', 'Miriam', 'Zapp'),
    array('get', 'Geraldine', 'Travers'),
    array('rb426', 'Rose', 'Broadley'),
    array('jh684', 'Jill', 'Holliday'),
    array('rjm26', 'Rosalyn', 'Masterton'),
    array('kjcr', 'K.J.C.', 'Robins'),
    array('mke', 'Mark', 'Ellis'),
    array('cpb2', 'Chris', 'Barron'),
    array('ps93', 'Paul', 'Sinnock'),
    array('ltw', 'Les', 'Walczowski'),
    array('tet', 'Tina', 'Thompson'),
    array('ejr', 'Emma', 'Robinson'),
    array('km408', 'Katie', 'Marshall'),
    array('aac', 'Alan', 'Carruth'),
    array('seb64', 'Siobhan', 'Buckingham'),
    array('jh389', 'James', 'Holdsworth'),
    array('ces25', 'Claire', 'Smith'),
    array('nd227', 'Natasha', 'Deakin'),
    array('lbc', 'Lauren', 'Cooper'),
    array('dd254', 'Debby', 'Darby'),
    array('al374', 'Annikki', 'Laitinen'),
    array('pr84', 'Pauline', 'Rogers'),
    array('pmb2', 'Trish', 'Barton'),
    array('jsw', 'Jenifer', 'Wilkinson'),
    array('gw', 'Gill', 'Warr'),
    array('lt217', 'Lisa', 'Towers'),
    array('pg52', 'Paul', 'Glover'),
    array('lp336', 'Lucie', 'Patch'),
    array('dg73', 'D.', 'Gardner'),
    array('jm233', 'Jahanara', 'Ahmed'),
    array('rg241', 'Rejane', 'Gwynne'),
    array('ms728', 'Madalin', 'Simeria'),
    array('ss30', 'Suzanne', 'Smith'),
    array('kp329', 'Kelly', 'Pawley'),
    array('pg52', 'Paul', 'Glover'),
    array('kg60', 'Kalliopi', 'Glezakou'),
    array('cd341', 'Caroline', 'Davies'),
    array('jr453', 'Justine', 'Reid'),
    array('dk9', 'Derek', 'Kirton'),
    array('mm595', 'Mita', 'Mondal'),
    array('mb485', 'M.', 'Basit'),
    array('sm687', 'Sarah', 'Marsh'),
    array('hms', 'Hayley', 'Scales'),
    array('jrr', 'James', 'Redmond'),
    array('mac45', 'Miles', 'Coulling'),
    array('slb44', 'Samantha', 'Betts'),
    array('bw68', 'Ben', 'Watson'),
    array('ab684', 'Amanda', 'Banfield'),
    array('jld2', 'Jo', 'Dunlop'),
    array('kh207', 'Kyra', 'Harwood-Lucas'),
    array('sb79', 'Sarah', 'Edwards'),
    array('sbh', 'Stephanie', 'Harris'),
    array('kap', 'Kelly', 'Porter'),
    array('maw8', 'Maureen', 'Wilson'),
    array('tcg', 'Tina', 'Grove'),
    array('gmd5', 'Mark', 'Dean'),
    array('ap371', 'Amy', 'Parkes'),
    array('cla20', 'Claire', 'Ashton'),
    array('lb353', 'Lydia', 'Burchett'),
    array('ljl2', 'Lesley', 'Lawrence'),
    array('krm', 'Kim', 'Martin'),
    array('lm487', 'Lucy', 'Martin'),
    array('eji2', 'Jayne', 'Instone'),
    array('gmd5', 'Mark', 'Dean'),
    array('mac45', 'Miles', 'Coulling'),
    array('idcr', 'Iain', 'Ramsay'),
    array('drl', 'Daniel', 'Lee'),
    array('nsrj', 'Nick', 'Jackson'),
    array('ng282', 'N.', 'Gregory'),
    array('jah85', 'Julie', 'Henson'),
    array('aps42', 'Andrea', 'Shieber'),
    array('gac', 'Gemma', 'Chapman'),
    array('sr259', 'Suzie', 'Westhead'),
    array('nc12', 'Nicola', 'Huxtable'),
    array('rdc', 'Robert', 'Chapman'),
    array('rb380', 'Rubrick', 'Biegon'),
    array('jmv5', 'J.M.', 'Veloso-do-Amaral'),
    array('jh525', 'Jessica', 'Shepheard'),
    array('tp256', 'Dora', 'Perera'),
    array('sld', 'Sara', 'Witchell'),
    array('if34', 'I.', 'Friesen'),
    array('pa213', 'P.', 'Ashby'),
    array('amj29', 'A.M.', 'Jeffs'),
    array('rbm9', 'Rosemary', 'Miller'),
    array('sp540', 'S.L.', 'Punt'),
    array('cet34', 'Claire', 'Tanner'),
    array('sd464', 'Sophia', 'Dixon'),
    array('ag92', 'Andy', 'Galbraith'),
    array('kcd', 'Kristina Charlotte', 'Dietz'),
    array('lm292', 'Laura', 'McPherson'),
    array('ap414', 'Sakis', 'Pappous'),
    array('bm264', 'Brian', 'Minikin'),
    array('jwd', 'John', 'Dickinson'),
    array('ljh', 'Lucy', 'Hale'),
    array('mb600', 'Mark', 'Burnley'),
    array('cm491', 'Carla', 'Meijen'),
    array('csg', 'Claire', 'Graham'),
    array('slw49', 'Samantha', 'Winter'),
    array('sm', 'Steve', 'Meadows'),
    array('kd57', 'Kyra', 'De Coninck'),
    array('lm415', 'Lex', 'Mauger'),
    array('lp217', 'Louis', 'Passfield'),
    array('kh275', 'Karen', 'Hambly'),
    array('smm', 'Samuele', 'Marcora'),
    array('kcd', 'Kristina Charlotte', 'Dietz'),
    array('dmt29', 'Deana', 'Twyman'),
    array('gd207', 'Glen', 'Davison'),
    array('jgh', 'James', 'Hopker'),
    array('wpr5', 'Will', 'Radford'),
    array('rec46', 'Ruth', 'Cox'),
    array('nsj', 'Nicola', 'Johnson'),
    array('wpr5', 'Will', 'Radford'),
    array('ram7', 'Richard', 'Millns'),
    array('km435', 'Karthikeyan', 'Muthumayandi'),
    array('mjf46', 'Michaela', 'Fullman'),
    array('ljw', 'Lyndsay', 'Whiting'),
    array('hgw', 'Hayley', 'White'),
    array('cbt', 'Charlie', 'Tickle'),
    array('ale', 'Anna', 'Cole'),
    array('jea4', 'Janine', 'Anderson'),
    array('gat', 'Gerard', 'Tappenden'),
    array('pmjv', 'Paul', 'Verrion'),
    array('pr84', 'Pauline', 'Rogers'),
    array('ncm', 'Nicola', 'Moys'),
    array('dg73', 'D.', 'Gardner'),
    array('gcp', 'Giles', 'Polglase'),
    array('pmjv', 'Paul', 'Verrion'),
    array('hgw', 'Hayley', 'White'),
    array('ale', 'Anna', 'Cole'),
    array('aa783', 'A.', 'Anastasiu'),
    array('as802', 'Nancy', 'Spyridakou'),
    array('lj212', 'L.T.', 'Jackson'),
    array('djl', 'Des', 'Laffey'),
    array('trh1', 'Tamsin', 'Harris'),
    array('gat', 'Gerard', 'Tappenden'),
    array('sb842', 'S.A.W.', 'Botha'),
    array('la', 'Lizanne', 'Allcock'),
    array('ja356', 'John', 'Allen'),
    array('tf224', 'Tom', 'Finley'),
    array('gs', 'Gary', 'Samson'),
    array('maf1', 'Michael', 'Forrester'),
    array('lac48', 'Lisa', 'Clark'),
    array('elr', 'Esme', 'Rigden'),
    array('vaw6', 'Vicky', 'Ward'),
    array('slw45', 'Sarah', 'Whitfield'),
    array('kas3', 'Kate', 'Scott'),
    array('cb386', 'Carly', 'Turnham'),
    array('vaw6', 'Vicky', 'Ward'),
    array('acb40', 'Adam', 'Britcher'),
    array('gr', 'Georgina', 'Randsley de Moura'),
    array('th16', 'Tim', 'Hopthrow'),
    array('fg30', 'Frank', 'Gasking'),
    array('nw201', 'Natalia', 'Weller'),
    array('ka231', 'Kirsten', 'Abbot-Smith'),
    array('da3', 'Dominic', 'Abrams'),
    array('ekaa', 'Emma', 'Alleyne'),
    array('zmb', 'Zara', 'Bergstrom'),
    array('mb531', 'Markus', 'Bindemann'),
    array('jb215', 'Janet', 'Briggs'),
    array('jlb52', 'Joseph', 'Brooks'),
    array('ab696', 'Anna', 'Brown'),
    array('rc394', 'Rachel', 'Calogero'),
    array('lc35', 'Lindsey', 'Cameron'),
    array('akc9', 'Aleksandra', 'Cichocka'),
    array('kd50', 'Karen', 'Douglas'),
    array('hf63', 'Heather', 'Ferguson'),
    array('tag6', 'Theresa', 'Gannon'),
    array('rsg', 'Roger', 'Giner-Sorolla'),
    array('th16', 'Tim', 'Hopthrow'),
    array('lk255', 'Lydia', 'Kearney'),
    array('nlk4', 'Norbert L', 'Kerr'),
    array('ac540', 'Ana', 'Leite'),
    array('en67', 'Erika', 'Nurmsoo'),
    array('cco4', 'Caoilte', 'O Ciardha'),
    array('ap362', 'Afroditi', 'Pina'),
    array('cp439', 'Christos', 'Pliatsikas'),
    array('gr', 'Georgina', 'Randsley de Moura'),
    array('jvs', 'Janet', 'Sayers'),
    array('ds9', 'Dinkar', 'Sharma'),
    array('rs214', 'Robbie', 'Sutton'),
    array('aku3', 'Ayse', 'Uskul'),
    array('ajmv', 'Annemieke', 'Van den Tol'),
    array('ev46', 'Eduardo', 'Vasquez'),
    array('gtv2', 'Tendayi', 'Viki'),
    array('mw304', 'Mario', 'Weick'),
    array('dtw', 'David', 'Wilkinson'),
    array('dmw38', 'David', 'Williams'),
    array('kew30', 'Katherine', 'Wilson'),
    array('aw88', 'Arnaud', 'Wisman'),
    array('jlw3', 'Jane', 'Wood'),
    array('cp447', 'C.', 'Powell'),
    array('fs245', 'F.', 'Samra'),
    array('jsh31', 'Jennie', 'Hogg'),
    array('cme', 'Christine', 'Eagle'),
    array('es344', 'Emma', 'Spiller'),
    array('nak1', 'Nicola', 'Kerry-Yoxall'),
    array('lb322', 'L.', 'Betti'),
    array('ajmk3', 'A.J.M.', 'Key'),
    array('kg254', 'K.', 'Greenway'),
    array('sepb', 'Samantha', 'Barnes'),
    array('ka297', 'Kate', 'Ayres'),
    array('ab797', 'Ashleigh', 'Francis'),
    array('lw220', 'Laura', 'Withers'),
    array('bw68', 'Ben', 'Watson'),
    array('ng282', 'N.', 'Gregory'),
    array('lal24', 'Linda', 'Le Grys'),
    array('hss', 'Helen', 'Smith'),
    array('kl267', 'Kirsty', 'Logan'),
    array('mm595', 'Mita', 'Mondal'),
    array('cs614', 'C.', 'Sanderson'),
    array('pmb2', 'Trish', 'Barton'),
    array('jdb6', 'Julie', 'Beadle-Brown'),
    array('pt200', 'Paraskevi', 'Triantafyllopoulou'),
    array('pt200', 'Paraskevi', 'Triantafyllopoulou'),
    array('lw', 'Lynn', 'Risbridger'),
    array('dw216', 'Dylan', 'Williams'),
    array('kf80', 'Karen', 'Finch'),
    array('sr476', 'S.', 'Robertson'),
    array('pjh', 'Paul', 'Hubert'),
    array('hrp', 'Hattie', 'Peacocke'),
    array('jmh30', 'Joanne', 'Harvey'),
    array('pr84', 'Pauline', 'Rogers'),
    array('rb241', 'Rhea', 'Ball'),
    array('bac', 'Barbara', 'Criddle'),
    array('jca', 'Juliette', 'Dack'),
    array('clt9', 'Claire', 'Taylor'),
    array('jg319', 'Jessica', 'Gilbert'),
    array('hjw', 'Helen', 'Winder'),
    array('jms2', 'Julie', 'Scott'),
    array('am595', 'Anthony', 'Manning'),
    array('ham', 'Hannah', 'McNorton'),
    array('gjm32', 'Georgia', 'Miller'),
    array('am686', 'Amy', 'Moses'),
    array('sc346', 'Sebastien', 'Cadinot'),
    array('fn23', 'Fumiyo', 'Nemoto-Smith'),
    array('cm431', 'Carla', 'Morris'),
    array('jrn5', 'Ruth', 'Newman'),
    array('ks507', 'Kieran', 'Shand'),
    array('kab56', 'Katie', 'Baldock'),
    array('js246', 'Jeanne', 'Straight'),
    array('eg291', 'Ellie', 'Graham'),
    array('jm757', 'Jan', 'Moriarty'),
    array('bam', 'Ben', 'Martin'),
    array('bw62', 'Brian', 'Wood'),
    array('vf46', 'Victoria', 'Friedman'),
    array('aidh', 'Alice', 'Hamilton'),
    array('rv85', 'R.', 'Vaitkeviciute'),
    array('dh287', 'David', 'Haney'),
    array('ga47', 'Gerry', 'Adler'),
    array('dg74', 'Don', 'Gray'),
    array('jb550', 'Jon', 'Beer'),
    array('cr492', 'Chloe', 'Robbins'),
    array('lsw4', 'Leonie', 'Wells-Furby'),
    array('zd30', 'Zoe', 'Denness'),
    array('tpk', 'Tim', 'Keward'),
    array('jb550', 'Jon', 'Beer'),
    array('cr492', 'Chloe', 'Robbins'),
    array('tpk', 'Tim', 'Keward'),
    array('ejeb', 'Eloise', 'Bates'),
    array('slmc', 'Sam', 'Crooks'),
    array('rsb38', 'Rob', 'Brown'),
    array('slg', 'Stephanie', 'Green'),
    array('jd403', 'Mary', 'Daly'),
    array('dbf', 'Denny', 'Flowers'),
    array('db348', 'Daniel', 'Blackman'),
    array('cn67', 'Coralie', 'Norwood'),
    array('sah53', 'Simon', 'Hicks'),
    array('ge', 'Gemma', 'Eves'),
    array('jm452', 'Jacqui', 'Martlew'),
    array('famg', 'Fiona', 'Godfrey'),
    array('jrh38', 'Jessica', 'Holland'),
    array('jrh38', 'Jessica', 'Holland'),
    array('rjs69', 'R.J.', 'Stack'),
    array('rjs73', 'Richard', 'Stack'),
    array('cb244', 'Kate', 'Buchan'),
    array('ab874', 'Ayesha', 'Barnes'),
    array('ar444', 'Alyx', 'Robinson'),
    array('clt9', 'Claire', 'Taylor'),
    array('re34', 'Rachel', 'Evans'),
    array('fc94', 'Ffion', 'Capelin'),
    array('re34', 'Rachel', 'Evans'),
    array('fc94', 'Ffion', 'Capelin'),
    array('ps357', 'Paul', 'Sharp'),
    array('mk361', 'Mike', 'Keeling-Smith'),
    array('scs2', 'Sue', 'Sherwood'),
    array('ajw24', 'Angela', 'Whiffen'),
    array('asg28', 'Amy', 'Green'),
    array('jd461', 'Jacqui', 'Double'),
    array('cl309', 'Claire-Ann', 'Lyons'),
    array('ag335', 'Andrea', 'Griffith'),
    array('mb635', 'Megan', 'Barrett'),
    array('gmt3', 'Gill', 'Tobin'),
    array('ad417', 'Aimee', 'Dash'),
    array('fv20', 'Faith', 'Phoenix'),
    array('eb', 'Emma', 'Bainbridge'),
    array('ks440', 'Kim', 'Simpson'),
    array('jd359', 'Jenny', 'DiPlacidi'),
    array('mm538', 'Monica', 'Mattfeld'),
    array('gl205', 'Graham', 'Lewis'),
    array('brlc', 'Brigid', 'Carroll'),
    array('set', 'Sarah', 'Turner'),
    array('fw56', 'Frank', 'Walker'),
    array('ljf', 'Louise', 'Frith'),
    array('lj212', 'L.T.', 'Jackson'),
    array('tm356', 'Tom', 'McCormick'),
    array('bjac', 'Ben', 'Curry'),
    array('mem', 'M E', 'Malekia'),
    array('cmh41', 'Catherine', 'Hill'),
    array('cjf', 'Charlie', 'Fleming'),
    array('cm674', 'Charlie', 'Mayes'),
    array('knd4', 'Kevin', 'Dawe'),
    array('sa591', 'Sian', 'Anderson'),
    array('hka', 'Kristoffer', 'Ahlstrom-Vij'),
    array('ek241', 'Edward', 'Kanterian'),
    array('jm687', 'Julien', 'Murzi'),
    array('kcr', 'Kelli', 'Rudolph'),
    array('jt', 'Julia', 'Tanney'),
    array('lvr', 'Lubomira', 'Radoilska'),
    array('cs570', 'C.', 'Sandis'),
    array('jrc29', 'Jeremy', 'Carrette'),
    array('ah654', 'A.', 'Hass'),
    array('rek5', 'Richard', 'King'),
    array('jrh38', 'Jessica', 'Holland'),
    array('apa', 'Anne', 'Alwis'),
    array('za63', 'Z.', 'Archibald'),
    array('rgh4', 'R.G.', 'Hawley'),
    array('jm452', 'Jacqui', 'Martlew'),
    array('tw263', 'T.', 'Williams'),
    array('sg513', 'S.', 'Gounaris'),
    array('bs247', 'B.', 'Schultis'),
    array('gb325', 'G.', 'Bouchard'),
    array('pr208', 'P.', 'Reid'),
    array('ps357', 'Paul', 'Sharp'),
    array('mjt45', 'M.J.', 'Temple'),
    array('ps357', 'Paul', 'Sharp'),
    array('sl397', 'S.', 'Lee'),
    array('esgi', 'Shona', 'Illingworth'),
    array('th279', 'Tim', 'Howle'),
    array('ph69', 'Peter', 'Hatton'),
    array('esgi', 'Shona', 'Illingworth')
);

cli_heading("Updating all the users");

$done = array();
foreach ($users as $obj) {
    $username = \core_text::convert($obj[0], 'utf-8', 'utf-8');

    if (isset($done[$username])) {
        continue;
    }

    $user = $DB->get_record('user', array(
        'username' => $username
    ));

    if ($user->firstname != $obj[1] || $user->lastname != $obj[2]) {
        $user->firstname = $obj[1];
        $user->lastname = $obj[2];

        user_update_user($user, false);

        $done[$username] = true;
    }
}