<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

define('CLI_SCRIPT', true);

require_once(dirname(__FILE__) . '/../../../config.php');
require_once($CFG->libdir . '/clilib.php');

cli_heading("Doing all the role enrolments");

$roles = aray(
    array('sc5', 'School of Computing', 'dep_admin'),
    array('mcw', 'School of Computing', 'dep_admin'),
    array('tdb', 'School of Computing', 'support_staff'),
    array('rjh1', 'School of Computing', 'dep_admin'),
    array('das', 'School of Computing', 'dep_admin'),
    array('sm558', 'School of Computing', 'dep_admin'),
    array('jgj', 'School of Computing', 'dep_admin'),
    array('lj212', 'School of Computing', 'dep_admin'),
    array('la269', 'School of Computing', 'dep_admin'),
    array('sv39', 'School of Computing', 'dep_admin'),
    array('jt307', 'School of Computing', 'dep_admin'),
    array('tb222', 'School of Pharmacy', 'dep_admin'),
    array('smg', 'School of Pharmacy', 'support_staff'),
    array('rl222', 'School of Pharmacy', 'support_staff'),
    array('ssw', 'School of Pharmacy', 'support_staff'),
    array('vs59', 'School of Pharmacy', 'support_staff'),
    array('cd261', 'School of Pharmacy', 'support_staff'),
    array('jm294', 'School of Pharmacy', 'support_staff'),
    array('rh379', 'School of Pharmacy', 'support_staff'),
    array('hs235', 'School of Pharmacy', 'support_staff'),
    array('ah421', 'School of Pharmacy', 'support_staff'),
    array('tsg3', 'School of Pharmacy', 'support_staff'),
    array('mak23', 'School of Pharmacy', 'support_staff'),
    array('mnm', 'School of Pharmacy', 'support_staff'),
    array('es340', 'School of Pharmacy', 'support_staff'),
    array('amb54', 'School of Pharmacy', 'support_staff'),
    array('jr323', 'School of Pharmacy', 'support_staff'),
    array('yu', 'School of Pharmacy', 'support_staff'),
    array('vg65', 'School of Pharmacy', 'support_staff'),
    array('ib71', 'School of Pharmacy', 'support_staff'),
    array('am582', 'School of Pharmacy', 'support_staff'),
    array('rmw', 'School of Pharmacy', 'dep_admin'),
    array('jhajd', 'School of Pharmacy', 'support_staff'),
    array('an76', 'School of Pharmacy', 'support_staff'),
    array('aam23', 'School of Pharmacy', 'support_staff'),
    array('anl', 'School of Pharmacy', 'support_staff'),
    array('dl311', 'School of Pharmacy', 'support_staff'),
    array('ew208', 'School of Pharmacy', 'support_staff'),
    array('jfw4', 'School of Pharmacy', 'support_staff'),
    array('kc329', 'School of Pharmacy', 'support_staff'),
    array('kic', 'School of Pharmacy', 'support_staff'),
    array('mac', 'School of Pharmacy', 'support_staff'),
    array('rmr', 'School of Pharmacy', 'support_staff'),
    array('spk21', 'School of Pharmacy', 'support_staff'),
    array('sg260', 'School of Pharmacy', 'support_staff'),
    array('nt96', 'School of Pharmacy', 'support_staff'),
    array('tg41', 'School of Pharmacy', 'support_staff'),
    array('sac47', 'School of Pharmacy', 'support_staff'),
    array('km439', 'School of Pharmacy', 'support_staff'),
    array('aae', 'School of Pharmacy', 'support_staff'),
    array('nl48', 'School of Pharmacy', 'support_staff'),
    array('ng290', 'School of Pharmacy', 'support_staff'),
    array('cb355', 'School of Pharmacy', 'support_staff'),
    array('cd265', 'School of Pharmacy', 'support_staff'),
    array('gl53', 'School of Pharmacy', 'support_staff'),
    array('sds', 'School of Pharmacy', 'support_staff'),
    array('gw244', 'School of Pharmacy', 'support_staff'),
    array('ba75', 'School of Pharmacy', 'support_staff'),
    array('tt41', 'School of Pharmacy', 'support_staff'),
    array('lal22', 'School of Pharmacy', 'support_staff'),
    array('cmp34', 'School of Pharmacy', 'support_staff'),
    array('cmp36', 'School of Pharmacy', 'support_staff'),
    array('mh527', 'School of Pharmacy', 'support_staff'),
    array('jrr', 'School of Physical Sciences', 'dep_admin'),
    array('dcs', 'School of Physical Sciences', 'support_staff'),
    array('klh', 'School of Physical Sciences', 'dep_admin'),
    array('pnc', 'School of Physical Sciences', 'readinglist'),
    array('db400', 'School of Mathematics, Statistics and Actuarial Science', 'dep_admin'),
    array('kad5', 'School of Biosciences', 'dep_admin'),
    array('mz93', 'School of Biosciences', 'dep_admin'),
    array('get', 'School of Biosciences', 'support_staff'),
    array('rb426', 'School of Biosciences', 'support_staff'),
    array('jh684', 'School of Biosciences', 'dep_admin'),
    array('rjm26', 'School of Biosciences', 'dep_admin'),
    array('kjcr', 'School of Biosciences', 'support_staff'),
    array('mke', 'School of Engineering and Digital Arts', 'dep_admin'),
    array('cpb2', 'School of Engineering and Digital Arts', 'dep_admin'),
    array('ps93', 'School of Engineering and Digital Arts', 'support_staff'),
    array('ltw', 'School of Engineering and Digital Arts', 'dep_admin'),
    array('tet', 'School of Engineering and Digital Arts', 'support_staff'),
    array('ejr', 'School of Economics', 'dep_admin'),
    array('km408', 'School of Economics', 'support_staff'),
    array('aac', 'School of Economics', 'support_staff'),
    array('seb64', 'School of Economics', 'support_staff'),
    array('jh389', 'School of Economics', 'support_staff'),
    array('ces25', 'School of Social Policy, Sociology and Social Research', 'support_staff'),
    array('nd227', 'School of Social Policy, Sociology and Social Research', 'support_staff'),
    array('lbc', 'School of Social Policy, Sociology and Social Research', 'support_staff'),
    array('dd254', 'School of Social Policy, Sociology and Social Research', 'support_staff'),
    array('al374', 'School of Social Policy, Sociology and Social Research', 'support_staff'),
    array('pr84', 'School of Social Policy, Sociology and Social Research', 'support_staff'),
    array('pmb2', 'School of Social Policy, Sociology and Social Research', 'support_staff'),
    array('jsw', 'School of Social Policy, Sociology and Social Research', 'support_staff'),
    array('gw', 'School of Social Policy, Sociology and Social Research', 'support_staff'),
    array('lt217', 'School of Social Policy, Sociology and Social Research', 'support_staff'),
    array('pg52', 'School of Social Policy, Sociology and Social Research', 'support_staff'),
    array('lp336', 'School of Social Policy, Sociology and Social Research', 'support_staff'),
    array('dg73', 'School of Social Policy, Sociology and Social Research', 'support_staff'),
    array('jm233', 'School of Social Policy, Sociology and Social Research', 'support_staff'),
    array('rg241', 'School of Social Policy, Sociology and Social Research', 'support_staff'),
    array('ms728', 'School of Social Policy, Sociology and Social Research', 'support_staff'),
    array('ss30', 'School of Social Policy, Sociology and Social Research', 'support_staff'),
    array('kp329', 'School of Social Policy, Sociology and Social Research', 'support_staff'),
    array('pg52', 'School of Social Policy, Sociology and Social Research', 'dep_admin'),
    array('kg60', 'School of Social Policy, Sociology and Social Research', 'dep_admin'),
    array('cd341', 'School of Social Policy, Sociology and Social Research', 'support_staff'),
    array('jr453', 'School of Social Policy, Sociology and Social Research', 'support_staff'),
    array('dk9', 'School of Social Policy, Sociology and Social Research', 'marker'),
    array('mm595', 'School of Social Policy, Sociology and Social Research', 'readinglist'),
    array('mb485', 'School of Social Policy, Sociology and Social Research', 'support_staff'),
    array('sm687', 'School of Social Policy, Sociology and Social Research', 'support_staff'),
    array('hms', 'School of Social Policy, Sociology and Social Research', 'support_staff'),
    array('jrr', 'School of Social Policy, Sociology and Social Research', 'dep_admin'),
    array('pmb2', 'Tizard (TZ)', 'support_staff'),
    array('jdb6', 'Tizard (TZ)', 'dep_admin'),
    array('pt200', 'Tizard (TZ)', 'support_staff'),
    array('pt200', 'Tizard (TZ)', 'dep_admin'),
    array('mac45', 'Kent Law School', 'dep_admin'),
    array('slb44', 'Kent Law School', 'support_staff'),
    array('bw68', 'Kent Law School', 'support_staff'),
    array('ab684', 'Kent Law School', 'support_staff'),
    array('jld2', 'Kent Law School', 'support_staff'),
    array('kh207', 'Kent Law School', 'support_staff'),
    array('sb79', 'Kent Law School', 'support_staff'),
    array('sbh', 'Kent Law School', 'support_staff'),
    array('kap', 'Kent Law School', 'support_staff'),
    array('maw8', 'Kent Law School', 'support_staff'),
    array('tcg', 'Kent Law School', 'support_staff'),
    array('gmd5', 'Kent Law School', 'support_staff'),
    array('ap371', 'Kent Law School', 'support_staff'),
    array('cla20', 'Kent Law School', 'support_staff'),
    array('lb353', 'Kent Law School', 'support_staff'),
    array('ljl2', 'Kent Law School', 'support_staff'),
    array('krm', 'Kent Law School', 'support_staff'),
    array('lm487', 'Kent Law School', 'support_staff'),
    array('eji2', 'Kent Law School', 'support_staff'),
    array('gmd5', 'Kent Law School', 'panopto_creator'),
    array('mac45', 'Kent Law School', 'panopto_creator'),
    array('idcr', 'Kent Law School', 'support_staff'),
    array('drl', 'Kent Law School', 'support_staff'),
    array('nsrj', 'Kent Law School', 'support_staff'),
    array('ng282', 'Kent Law School', 'support_staff'),
    array('jah85', 'Kent Law School', 'support_staff'),
    array('aps42', 'Kent Law School', 'support_staff'),
    array('lw', 'Postgraduate', 'support_staff'),
    array('dw216', 'Postgraduate', 'support_staff'),
    array('kf80', 'Postgraduate', 'support_staff'),
    array('sr476', 'Postgraduate', 'support_staff'),
    array('pjh', 'Undergraduate', 'support_staff'),
    array('hrp', 'Undergraduate', 'support_staff'),
    array('jmh30', 'Undergraduate', 'support_staff'),
    array('pr84', 'Undergraduate', 'support_staff'),
    array('rb241', 'Undergraduate', 'support_staff'),
    array('gac', 'School of Politics and International Relations', 'dep_admin'),
    array('sr259', 'School of Politics and International Relations', 'dep_admin'),
    array('nc12', 'School of Politics and International Relations', 'dep_admin'),
    array('rdc', 'School of Politics and International Relations', 'support_staff'),
    array('rb380', 'School of Politics and International Relations', 'readinglist'),
    array('jmv5', 'School of Politics and International Relations', 'readinglist'),
    array('jh525', 'School of Politics and International Relations', 'dep_admin'),
    array('tp256', 'School of Politics and International Relations', 'dep_admin'),
    array('sld', 'School of Politics and International Relations', 'support_staff'),
    array('if34', 'School of Politics and International Relations', 'readinglist'),
    array('pa213', 'School of Politics and International Relations', 'readinglist'),
    array('amj29', 'School of Politics and International Relations', 'readinglist'),
    array('rbm9', 'School of Politics and International Relations', 'dep_admin'),
    array('sp540', 'School of Politics and International Relations', 'dep_admin'),
    array('cet34', 'School of Politics and International Relations', 'dep_admin'),
    array('sd464', 'School of Politics and International Relations', 'support_staff'),
    array('bac', 'UELT (UN)', 'dep_admin'),
    array('ag92', 'Centre for Sports Studies', 'dep_admin'),
    array('kcd', 'Centre for Sports Studies', 'teacher'),
    array('lm292', 'Centre for Sports Studies', 'support_staff'),
    array('ap414', 'Centre for Sports Studies', 'support_staff'),
    array('bm264', 'Centre for Sports Studies', 'support_staff'),
    array('jwd', 'Centre for Sports Studies', 'support_staff'),
    array('ljh', 'Centre for Sports Studies', 'support_staff'),
    array('mb600', 'Centre for Sports Studies', 'support_staff'),
    array('cm491', 'Centre for Sports Studies', 'support_staff'),
    array('csg', 'Centre for Sports Studies', 'support_staff'),
    array('slw49', 'Centre for Sports Studies', 'support_staff'),
    array('sm', 'Centre for Sports Studies', 'support_staff'),
    array('kd57', 'Centre for Sports Studies', 'support_staff'),
    array('lm415', 'Centre for Sports Studies', 'support_staff'),
    array('lp217', 'Centre for Sports Studies', 'support_staff'),
    array('kh275', 'Centre for Sports Studies', 'support_staff'),
    array('smm', 'Centre for Sports Studies', 'support_staff'),
    array('kcd', 'Centre for Sports Studies', 'support_staff'),
    array('dmt29', 'Centre for Sports Studies', 'support_staff'),
    array('gd207', 'Centre for Sports Studies', 'support_staff'),
    array('jgh', 'Centre for Sports Studies', 'support_staff'),
    array('wpr5', 'Centre for Sports Studies', 'teacher'),
    array('rec46', 'Centre for Sports Studies', 'support_staff'),
    array('nsj', 'Centre for Sports Studies', 'support_staff'),
    array('wpr5', 'Centre for Sports Studies', 'support_staff'),
    array('ram7', 'Centre for Sports Studies', 'support_staff'),
    array('km435', 'Centre for Sports Studies', 'support_staff'),
    array('mjf46', 'Centre for Sports Studies', 'teacher'),
    array('ljw', 'Kent Business School', 'dep_admin'),
    array('hgw', 'Kent Business School', 'dep_admin'),
    array('cbt', 'Kent Business School', 'dep_admin'),
    array('ale', 'Kent Business School', 'dep_admin'),
    array('jea4', 'Kent Business School', 'dep_admin'),
    array('gat', 'Kent Business School', 'dep_admin'),
    array('pmjv', 'Kent Business School', 'dep_admin'),
    array('pr84', 'Kent Business School', 'support_staff'),
    array('ncm', 'Kent Business School', 'support_staff'),
    array('dg73', 'Kent Business School', 'dep_admin'),
    array('gcp', 'Kent Business School', 'dep_admin'),
    array('pmjv', 'Kent Business School', 'readinglist'),
    array('hgw', 'Kent Business School', 'readinglist'),
    array('ale', 'Kent Business School', 'readinglist'),
    array('aa783', 'Kent Business School', 'readinglist'),
    array('as802', 'Kent Business School', 'dep_admin'),
    array('lj212', 'Kent Business School', 'dep_admin'),
    array('djl', 'Kent Business School', 'support_staff'),
    array('trh1', 'Kent Business School', 'dep_admin'),
    array('gat', 'Kent Business School', 'panopto_creator'),
    array('sb842', 'Kent Business School', 'support_staff'),
    array('la', 'School of Psychology', 'dep_admin'),
    array('ja356', 'School of Psychology', 'support_staff'),
    array('tf224', 'School of Psychology', 'dep_admin'),
    array('gs', 'School of Psychology', 'support_staff'),
    array('maf1', 'School of Psychology', 'teacher'),
    array('lac48', 'School of Psychology', 'support_staff'),
    array('elr', 'School of Psychology', 'support_staff'),
    array('vaw6', 'School of Psychology', 'support_staff'),
    array('slw45', 'School of Psychology', 'support_staff'),
    array('kas3', 'School of Psychology', 'support_staff'),
    array('cb386', 'School of Psychology', 'support_staff'),
    array('vaw6', 'School of Psychology', 'dep_admin'),
    array('acb40', 'School of Psychology', 'support_staff'),
    array('gr', 'School of Psychology', 'support_staff'),
    array('th16', 'School of Psychology', 'support_staff'),
    array('fg30', 'School of Psychology', 'dep_admin'),
    array('nw201', 'School of Psychology', 'support_staff'),
    array('ka231', 'School of Psychology', 'teacher'),
    array('da3', 'School of Psychology', 'teacher'),
    array('ekaa', 'School of Psychology', 'teacher'),
    array('zmb', 'School of Psychology', 'teacher'),
    array('mb531', 'School of Psychology', 'teacher'),
    array('jb215', 'School of Psychology', 'teacher'),
    array('jlb52', 'School of Psychology', 'teacher'),
    array('ab696', 'School of Psychology', 'teacher'),
    array('rc394', 'School of Psychology', 'teacher'),
    array('lc35', 'School of Psychology', 'teacher'),
    array('akc9', 'School of Psychology', 'teacher'),
    array('kd50', 'School of Psychology', 'teacher'),
    array('hf63', 'School of Psychology', 'teacher'),
    array('tag6', 'School of Psychology', 'teacher'),
    array('rsg', 'School of Psychology', 'teacher'),
    array('th16', 'School of Psychology', 'teacher'),
    array('lk255', 'School of Psychology', 'teacher'),
    array('nlk4', 'School of Psychology', 'teacher'),
    array('ac540', 'School of Psychology', 'teacher'),
    array('en67', 'School of Psychology', 'teacher'),
    array('cco4', 'School of Psychology', 'teacher'),
    array('ap362', 'School of Psychology', 'teacher'),
    array('cp439', 'School of Psychology', 'teacher'),
    array('gr', 'School of Psychology', 'teacher'),
    array('jvs', 'School of Psychology', 'teacher'),
    array('ds9', 'School of Psychology', 'teacher'),
    array('rs214', 'School of Psychology', 'teacher'),
    array('aku3', 'School of Psychology', 'teacher'),
    array('ajmv', 'School of Psychology', 'teacher'),
    array('ev46', 'School of Psychology', 'teacher'),
    array('gtv2', 'School of Psychology', 'teacher'),
    array('mw304', 'School of Psychology', 'teacher'),
    array('dtw', 'School of Psychology', 'teacher'),
    array('dmw38', 'School of Psychology', 'teacher'),
    array('kew30', 'School of Psychology', 'teacher'),
    array('aw88', 'School of Psychology', 'teacher'),
    array('jlw3', 'School of Psychology', 'teacher'),
    array('cp447', 'School of Psychology', 'teacher'),
    array('fs245', 'School of Psychology', 'support_staff'),
    array('jsh31', 'School of Anthropology and Conservation', 'support_staff'),
    array('cme', 'School of Anthropology and Conservation', 'dep_admin'),
    array('es344', 'School of Anthropology and Conservation', 'dep_admin'),
    array('nak1', 'School of Anthropology and Conservation', 'support_staff'),
    array('lb322', 'School of Anthropology and Conservation', 'readinglist'),
    array('ajmk3', 'School of Anthropology and Conservation', 'readinglist'),
    array('kg254', 'School of Anthropology and Conservation', 'readinglist'),
    array('sepb', 'School of Anthropology and Conservation', 'dep_admin'),
    array('ka297', 'School of Anthropology and Conservation', 'support_staff'),
    array('ab797', 'School of Anthropology and Conservation', 'support_staff'),
    array('lw220', 'School of Anthropology and Conservation', 'dep_admin'),
    array('bw68', 'School of Anthropology and Conservation', 'support_staff'),
    array('ng282', 'School of Anthropology and Conservation', 'readinglist'),
    array('lal24', 'Centre for Professional Practice', 'support_staff'),
    array('hss', 'Centre for Professional Practice', 'support_staff'),
    array('kl267', 'Centre for Professional Practice', 'dep_admin'),
    array('mm595', 'Centre for Professional Practice', 'dep_admin'),
    array('cs614', 'Centre for Professional Practice', 'support_staff'),
    array('clt9', 'Centre for Medieval and Early Modern Studies', 'dep_admin'),
    array('jg319', 'Centre for English and World Languages', 'support_staff'),
    array('hjw', 'Centre for English and World Languages', 'dep_admin'),
    array('jms2', 'Centre for English and World Languages', 'support_staff'),
    array('am595', 'Centre for English and World Languages', 'support_staff'),
    array('ham', 'Centre for English and World Languages', 'support_staff'),
    array('gjm32', 'Centre for English and World Languages', 'support_staff'),
    array('am686', 'Centre for English and World Languages', 'support_staff'),
    array('sc346', 'Centre for English and World Languages', 'dep_admin'),
    array('fn23', 'Centre for English and World Languages', 'support_staff'),
    array('cm431', 'Centre for English and World Languages', 'support_staff'),
    array('jrn5', 'Centre for English and World Languages', 'support_staff'),
    array('ks507', 'Centre for English and World Languages', 'support_staff'),
    array('kab56', 'Centre for English and World Languages', 'support_staff'),
    array('js246', 'School of Architecture', 'dep_admin'),
    array('eg291', 'School of Architecture', 'dep_admin'),
    array('jm757', 'School of Architecture', 'dep_admin'),
    array('bam', 'School of Architecture', 'dep_admin'),
    array('bw62', 'School of Architecture', 'dep_admin'),
    array('vf46', 'School of Architecture', 'dep_admin'),
    array('aidh', 'School of Architecture', 'dep_admin'),
    array('rv85', 'School of Architecture', 'dep_admin'),
    array('dh287', 'School of Architecture', 'dep_admin'),
    array('ga47', 'School of Architecture', 'dep_admin'),
    array('dg74', 'School of Architecture', 'dep_admin'),
    array('jb550', 'School of History', 'dep_admin'),
    array('cr492', 'School of History', 'dep_admin'),
    array('lsw4', 'School of History', 'support_staff'),
    array('zd30', 'School of History', 'support_staff'),
    array('tpk', 'School of History', 'dep_admin'),
    array('jb550', 'School of History', 'panopto_creator'),
    array('cr492', 'School of History', 'panopto_creator'),
    array('tpk', 'School of History', 'panopto_creator'),
    array('ejeb', 'School of History', 'dep_admin'),
    array('slmc', 'School of History', 'dep_admin'),
    array('rsb38', 'School of History', 'dep_admin'),
    array('slg', 'School of European Culture and Languages', 'support_staff'),
    array('jd403', 'School of European Culture and Languages', 'dep_admin'),
    array('db348', 'School of European Culture and Languages', 'dep_admin'),
    array('cn67', 'School of European Culture and Languages', 'dep_admin'),
    array('sah53', 'School of European Culture and Languages', 'dep_admin'),
    array('ge', 'School of European Culture and Languages', 'dep_admin'),
    array('jm452', 'School of European Culture and Languages', 'dep_admin'),
    array('famg', 'School of European Culture and Languages', 'dep_admin'),
    array('jrh38', 'School of European Culture and Languages', 'dep_admin'),
    array('jrh38', 'School of European Culture and Languages', 'support_staff'),
    array('rjs69', 'School of European Culture and Languages', 'dep_admin'),
    array('rjs73', 'School of European Culture and Languages', 'dep_admin'),
    array('cb244', 'School of European Culture and Languages', 'dep_admin'),
    array('ab874', 'School of European Culture and Languages', 'dep_admin'),
    array('ar444', 'School of European Culture and Languages', 'dep_admin'),
    array('hka', 'Philosophy (PL)', 'teacher'),
    array('ek241', 'Philosophy (PL)', 'teacher'),
    array('jm687', 'Philosophy (PL)', 'teacher'),
    array('kcr', 'Philosophy (PL)', 'teacher'),
    array('jt', 'Philosophy (PL)', 'teacher'),
    array('lvr', 'Philosophy (PL)', 'teacher'),
    array('cs570', 'Philosophy (PL)', 'teacher'),
    array('jrc29', 'Religious Studies (TH)', 'dep_admin'),
    array('ah654', 'Religious Studies (TH)', 'teacher'),
    array('rek5', 'Religious Studies (TH)', 'teacher'),
    array('jrh38', 'Classical & Archaeological Studies (CL)', 'support_staff'),
    array('apa', 'Classical & Archaeological Studies (CL)', 'teacher'),
    array('za63', 'Classical & Archaeological Studies (CL)', 'teacher'),
    array('rgh4', 'Classical & Archaeological Studies (CL)', 'teacher'),
    array('clt9', 'Centre for American Studies', 'dep_admin'),
    array('re34', 'School of Arts', 'support_staff'),
    array('re34', 'School of Arts', 'dep_admin'),
    array('ps357', 'School of Arts', 'dep_admin'),
    array('mk361', 'School of Arts', 'support_staff'),
    array('scs2', 'School of Arts', 'support_staff'),
    array('ajw24', 'School of Arts', 'support_staff'),
    array('asg28', 'School of Arts', 'dep_admin'),
    array('jd461', 'School of Arts', 'support_staff'),
    array('bs247', 'Drama & Theatre Studies (DR)', 'support_staff'),
    array('gb325', 'Drama & Theatre Studies (DR)', 'teacher'),
    array('pr208', 'Drama & Theatre Studies (DR)', 'teacher'),
    array('esgi', 'Music & Audio (MU)', 'support_staff'),
    array('th279', 'Music & Audio (MU)', 'support_staff'),
    array('ph69', 'Event & Experience Design (CR)', 'support_staff'),
    array('ps357', 'Film Studies (FI)', 'dep_admin'),
    array('mjt45', 'Film Studies (FI)', 'teacher'),
    array('ps357', 'History & Philosophy of Art (HA)', 'dep_admin'),
    array('sl397', 'History & Philosophy of Art (HA)', 'teacher'),
    array('esgi', 'Fine Art (FA)', 'support_staff'),
    array('cl309', 'School of English', 'support_staff'),
    array('ag335', 'School of English', 'support_staff'),
    array('mb635', 'School of English', 'support_staff'),
    array('gmt3', 'School of English', 'support_staff'),
    array('ad417', 'School of English', 'support_staff'),
    array('fv20', 'School of English', 'dep_admin'),
    array('eb', 'School of English', 'dep_admin'),
    array('ks440', 'School of English', 'support_staff'),
    array('jd359', 'School of English', 'support_staff'),
    array('mm538', 'School of English', 'support_staff'),
    array('sb453', 'Sample modules for training resources', 'support_staff'),
    array('sb453', 'Student Transition Modules', 'support_staff'),
    array('jm452', 'Heritage Management (HM)', 'support_staff'),
    array('tw263', 'Heritage Management (HM)', 'teacher'),
    array('sg513', 'Heritage Management (HM)', 'teacher'),
    array('gl205', 'School of Music and Fine Art', 'dep_admin'),
    array('brlc', 'School of Music and Fine Art', 'dep_admin'),
    array('set', 'School of Music and Fine Art', 'support_staff'),
    array('fw56', 'School of Music and Fine Art', 'support_staff'),
    array('ljf', 'School of Music and Fine Art', 'support_staff'),
    array('lj212', 'School of Music and Fine Art', 'dep_admin'),
    array('tm356', 'School of Music and Fine Art', 'dep_admin'),
    array('bjac', 'School of Music and Fine Art', 'support_staff'),
    array('mem', 'School of Music and Fine Art', 'support_staff'),
    array('cmh41', 'School of Music and Fine Art', 'support_staff'),
    array('cjf', 'School of Music and Fine Art', 'support_staff'),
    array('cm674', 'School of Music and Fine Art', 'dep_admin'),
    array('knd4', 'School of Music and Fine Art', 'support_staff'),
    array('sa591', 'School of Music and Fine Art', 'dep_admin'),
    array('sc346', 'Kent Extra', 'dep_admin'),
    array('jrn5', 'Kent Extra', 'support_staff'),
    array('ks507', 'Kent Extra', 'support_staff'),
    array('hjw', 'Kent Extra', 'support_staff'),
    array('am595', 'Kent Extra', 'support_staff'),
    array('gjm32', 'Kent Extra', 'support_staff'),
    array('jg319', 'Kent Extra', 'support_staff'),
    array('kab56', 'Kent Extra', 'support_staff')
);


foreach ($roles as $role) {
    $user = $DB->get_record('user', array('username' => $role[0]));


    if (!isset($user)) {
        $user = new \stdClass();
        $user->username = \core_text::convert($role[0], 'utf-8', 'utf-8');
        $user->email = $user->username . "@kent.ac.uk";
        $user->auth = "kentsaml";
        $user->password = "not cached";
        $user->confirmed = 1;
        $user->mnethostid = $CFG->mnet_localhost_id;
        $user->firstname = substr($user->username, 0, 1);
        $user->lastname = substr($user->username, 1, 2);

        user_create_user($user, false);
    }

    $category = $DB->get_record('course_categories', array('name' => $role[1]));
    $role = $DB->get_record('role', array('shortname' => $role[2]));

    if (!isset($user) || !isset($category) || !isset($role)) {
        echo 'We dont have everything we need! ' . $role[0] . ' ' . $role[1] . ' ' . $role[2] . "\n";
        continue;
    }

    $context = \context_coursecat::instance($category->id);
    if (!user_has_role_assignment($user->id, $role->id, $context->id)) {
        role_assign($role->id, $user->id, $context->id);
    }
}